name: Auto Deploy to Dokploy

on:
  pull_request:
    types: [closed]
    branches:
      - prod

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Dokploy deployment
        run: |
          echo "🚀 Triggering deployment on Dokploy after merge to pod..."
          curl -X POST "${{ secrets.DOKPLOY_DEPLOY_HOOK }}"
